package cn.vonce.sql.spring.service;

import cn.vonce.sql.config.SqlBeanMeta;
import cn.vonce.sql.exception.SqlBeanException;
import cn.vonce.sql.java.dao.MybatisSqlBeanDao;
import org.apache.ibatis.mapping.Environment;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.h2.jdbcx.JdbcDataSource;
import org.mybatis.spring.SqlSessionTemplate;
import org.mybatis.spring.transaction.SpringManagedTransactionFactory;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Arrays;

/**
 * 集成回归测试：Mybatis 实现的 insert 必须能取回自增 id。
 * <p>对应缺陷：{@code insertWithGeneratedKeys} 原先使用 {@code SqlSession#getConnection()}，
 * 而该连接来自 {@link SqlSessionTemplate} 代理——在没有 Spring 事务时会话会在返回连接之前被关闭，
 * 随后 {@code prepareStatement} 抛 “connection closed”，被包装为
 * {@code 插入并取回自增id失败: connection closed}。</p>
 * <p>覆盖场景：① 无 Spring 事务（原先必然失败）；② 存在 Spring 事务（连接应复用事务连接并随事务回滚）。</p>
 * <p>直接以 main 方式运行（与项目内其它测试风格一致）。</p>
 */
public class InsertGeneratedKeyIT {

    private static final String URL = "jdbc:h2:mem:flexsql_insert_it;DB_CLOSE_DELAY=-1";

    static int passed = 0;
    static int failed = 0;

    static void check(boolean cond, String msg) {
        if (cond) {
            passed++;
            System.out.println("[PASS] " + msg);
        } else {
            failed++;
            System.out.println("[FAIL] " + msg);
        }
    }

    /**
     * 使用 lite 配置（不加 {@code @Configuration}）：Spring 4.1 的 CGLIB 在 JDK9+ 上需要额外
     * {@code --add-opens} 才能增强配置类，lite 模式无需 CGLIB。
     */
    static class Ctx {

        @Bean
        DataSource dataSource() {
            JdbcDataSource dataSource = new JdbcDataSource();
            dataSource.setURL(URL);
            dataSource.setUser("sa");
            dataSource.setPassword("");
            return dataSource;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(DataSource dataSource) {
            org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
            configuration.setEnvironment(new Environment("it", new SpringManagedTransactionFactory(), dataSource));
            configuration.addMapper(MybatisSqlBeanDao.class);
            return new SqlSessionFactoryBuilder().build(configuration);
        }

        @Bean
        SqlSession sqlSession(SqlSessionFactory sqlSessionFactory) {
            return new SqlSessionTemplate(sqlSessionFactory);
        }

        @Bean
        MybatisSqlBeanDao<?> mybatisSqlBeanDao(SqlSession sqlSession) {
            return sqlSession.getMapper(MybatisSqlBeanDao.class);
        }

        @Bean(name = "sqlBeanConfigForMybatis")
        SqlBeanMeta sqlBeanMeta(SqlSessionFactory sqlSessionFactory) throws Exception {
            try (Connection connection = sqlSessionFactory.getConfiguration().getEnvironment().getDataSource().getConnection()) {
                return SqlBeanMeta.build(null, connection.getMetaData());
            }
        }

        @Bean
        ItUserService itUserService() {
            return new ItUserService();
        }

        @Bean
        DataSourceTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }
    }

    private static void createTable(DataSource dataSource) throws Exception {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS it_user");
            statement.execute("CREATE TABLE it_user ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "name VARCHAR(64),"
                    + "age INT)");
        }
    }

    public static void main(String[] args) throws Exception {
        AnnotationConfigApplicationContext ctx = new AnnotationConfigApplicationContext();
        ctx.register(Ctx.class);
        ctx.refresh();

        DataSource dataSource = ctx.getBean(DataSource.class);
        createTable(dataSource);

        ItUserService service = ctx.getBean(ItUserService.class);

        // 0. 复现根因：无 Spring 事务时 SqlSessionTemplate#getConnection() 返回的连接已被关闭
        SqlSessionTemplate rawTemplate = new SqlSessionTemplate(ctx.getBean(SqlSessionFactory.class));
        Connection rawConn = rawTemplate.getConnection();
        check(rawConn.isClosed(),
                "根因复现：无 Spring 事务时 SqlSessionTemplate#getConnection() 返回的连接已关闭（旧实现的报错来源）");

        // 1. 无 Spring 事务：单条插入应成功并回填自增 id
        ItUser first = new ItUser("Alice", 18);
        int count = 0;
        String error = null;
        try {
            count = service.insert(first);
        } catch (SqlBeanException e) {
            error = e.getMessage();
        }
        check(error == null, "无事务：insert 不应抛异常" + (error == null ? "" : "，实际=" + error));
        check(count == 1, "无事务：insert 返回受影响行数=1，实际=" + count);
        check(first.getId() != null && first.getId() == 1L,
                "无事务：自增 id 已回填到实体，实际=" + first.getId());

        // 2. 无 Spring 事务：集合批量插入应逐条回填 id
        ItUser second = new ItUser("Bob", 20);
        ItUser third = new ItUser("Cindy", 22);
        int batchCount = service.insert(Arrays.asList(second, third));
        check(batchCount == 2, "无事务：批量 insert 返回=2，实际=" + batchCount);
        check(second.getId() != null && second.getId() == 2L && third.getId() != null && third.getId() == 3L,
                "无事务：批量自增 id 依次回填，实际=" + second.getId() + "," + third.getId());

        // 3. 存在 Spring 事务：连接应复用事务连接，插入随事务提交
        DataSourceTransactionManager txManager = ctx.getBean(DataSourceTransactionManager.class);
        TransactionTemplate transactionTemplate = new TransactionTemplate(txManager);
        ItUser fourth = new ItUser("Dave", 30);
        transactionTemplate.execute(status -> service.insert(fourth));
        check(fourth.getId() != null && fourth.getId() == 4L,
                "有事务：自增 id 已回填，实际=" + fourth.getId());

        // 4. 存在 Spring 事务：异常回滚后数据不应落库
        int beforeRollback = service.count();
        try {
            transactionTemplate.execute(status -> {
                service.insert(new ItUser("Rollback", 40));
                throw new IllegalStateException("rollback for test");
            });
        } catch (IllegalStateException ignore) {
            // 预期异常
        }
        check(service.count() == beforeRollback,
                "有事务：回滚后不落库，期望=" + beforeRollback + "，实际=" + service.count());

        // 5. 事务结束后连接未泄漏：仍能继续插入
        ItUser fifth = new ItUser("Eve", 50);
        check(service.insert(fifth) == 1 && fifth.getId() != null,
                "有事务之后：连接可正常获取并继续插入，实际 id=" + fifth.getId());

        ctx.close();

        System.out.println();
        System.out.println("=== InsertGeneratedKeyIT: " + passed + " passed, " + failed + " failed ===");
        if (failed > 0) {
            System.exit(1);
        }
    }
}
