package cn.vonce.sql.spring.service;

import cn.vonce.sql.config.SqlBeanMeta;
import cn.vonce.sql.exception.SqlBeanException;
import cn.vonce.sql.java.dao.MybatisSqlBeanDao;
import org.apache.ibatis.mapping.Environment;
import org.apache.ibatis.session.SqlSession;
import org.apache.ibatis.session.SqlSessionFactory;
import org.apache.ibatis.session.SqlSessionFactoryBuilder;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.After;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mybatis.spring.SqlSessionTemplate;
import org.mybatis.spring.transaction.SpringManagedTransactionFactory;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.util.Arrays;

/**
 * 集成回归测试：Mybatis 实现的 insert 必须能取回自增 id。
 * <p>对应缺陷：{@code insertWithGeneratedKeys} 原先使用 {@code SqlSession#getConnection()}，
 * 而该连接来自 {@link SqlSessionTemplate} 代理——在没有 Spring 事务时会话会在返回连接之前被关闭，
 * 随后 {@code prepareStatement} 抛 “connection closed”，被包装为
 * {@code 插入并取回自增id失败: connection closed}。</p>
 * <p>覆盖场景：① 无 Spring 事务（原先必然失败）；② 存在 Spring 事务（连接应复用事务连接并随事务回滚）。</p>
 * <p>每个用例在 {@code @Before} 重建 Spring 上下文并重建 H2 表，因此自增 id 期望值（1/2/3）
 * 是确定的，且用例之间互不依赖。</p>
 */
public class InsertGeneratedKeyTest {

    private static final String URL = "jdbc:h2:mem:flexsql_insert_it;DB_CLOSE_DELAY=-1";

    private AnnotationConfigApplicationContext ctx;
    private ItUserService service;
    private SqlSessionTemplate rawTemplate;
    private DataSourceTransactionManager txManager;

    /**
     * 使用 lite 配置（不加 {@code @Configuration}）：Spring 4.1 的 CGLIB 在 JDK9+ 上需要额外
     * {@code --add-opens} 才能增强配置类，lite 模式无需 CGLIB。
     */
    static class Ctx {

        @Bean
        DataSource dataSource() {
            JdbcDataSource dataSource = new JdbcDataSource();
            dataSource.setURL(URL);
            dataSource.setUser("sa");
            dataSource.setPassword("");
            return dataSource;
        }

        @Bean
        SqlSessionFactory sqlSessionFactory(DataSource dataSource) {
            org.apache.ibatis.session.Configuration configuration = new org.apache.ibatis.session.Configuration();
            configuration.setEnvironment(new Environment("it", new SpringManagedTransactionFactory(), dataSource));
            configuration.addMapper(MybatisSqlBeanDao.class);
            return new SqlSessionFactoryBuilder().build(configuration);
        }

        @Bean
        SqlSession sqlSession(SqlSessionFactory sqlSessionFactory) {
            return new SqlSessionTemplate(sqlSessionFactory);
        }

        @Bean
        MybatisSqlBeanDao<?> mybatisSqlBeanDao(SqlSession sqlSession) {
            return sqlSession.getMapper(MybatisSqlBeanDao.class);
        }

        @Bean(name = "sqlBeanConfigForMybatis")
        SqlBeanMeta sqlBeanMeta(SqlSessionFactory sqlSessionFactory) throws Exception {
            try (Connection connection = sqlSessionFactory.getConfiguration().getEnvironment().getDataSource().getConnection()) {
                return SqlBeanMeta.build(null, connection.getMetaData());
            }
        }

        @Bean
        ItUserService itUserService() {
            return new ItUserService();
        }

        @Bean
        DataSourceTransactionManager transactionManager(DataSource dataSource) {
            return new DataSourceTransactionManager(dataSource);
        }
    }

    @Before
    public void setUp() throws Exception {
        ctx = new AnnotationConfigApplicationContext();
        ctx.register(Ctx.class);
        ctx.refresh();
        createTable(ctx.getBean(DataSource.class));
        service = ctx.getBean(ItUserService.class);
        rawTemplate = new SqlSessionTemplate(ctx.getBean(SqlSessionFactory.class));
        txManager = ctx.getBean(DataSourceTransactionManager.class);
    }

    @After
    public void tearDown() {
        if (ctx != null) {
            ctx.close();
        }
    }

    private static void createTable(DataSource dataSource) throws Exception {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("DROP TABLE IF EXISTS it_user");
            statement.execute("CREATE TABLE it_user ("
                    + "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                    + "name VARCHAR(64),"
                    + "age INT)");
        }
    }

    /** 复现根因：无 Spring 事务时 SqlSessionTemplate#getConnection() 返回的连接已被关闭。 */
    @Test
    public void sqlSessionTemplateConnectionIsClosedWithoutTransaction() throws Exception {
        Connection rawConn = rawTemplate.getConnection();
        Assert.assertTrue("根因复现：无 Spring 事务时 SqlSessionTemplate#getConnection() 返回的连接已关闭（旧实现的报错来源）",
                rawConn.isClosed());
    }

    /** 无 Spring 事务：单条插入应成功并回填自增 id。 */
    @Test
    public void singleInsertReturnsGeneratedKey() {
        ItUser first = new ItUser("Alice", 18);
        int count;
        try {
            count = service.insert(first);
        } catch (SqlBeanException e) {
            Assert.fail("无事务：insert 不应抛异常，实际=" + e.getMessage());
            return;
        }
        Assert.assertEquals("无事务：insert 返回受影响行数应为 1", 1, count);
        Assert.assertEquals("无事务：自增 id 应回填到实体", Long.valueOf(1L), first.getId());
    }

    /** 无 Spring 事务：集合批量插入应逐条回填 id。 */
    @Test
    public void batchInsertReturnsGeneratedKeys() {
        ItUser second = new ItUser("Bob", 20);
        ItUser third = new ItUser("Cindy", 22);
        Assert.assertEquals("无事务：批量 insert 返回应为 2", 2, service.insert(Arrays.asList(second, third)));
        // @Before 每用例重建空表，GENERATED BY DEFAULT AS IDENTITY 从 1 起算，故批量首条回填 1、次条回填 2。
        Assert.assertEquals("无事务：批量自增 id 应依次回填（第 1 条）", Long.valueOf(1L), second.getId());
        Assert.assertEquals("无事务：批量自增 id 应依次回填（第 2 条）", Long.valueOf(2L), third.getId());
    }

    /** 存在 Spring 事务：连接应复用事务连接，插入随事务提交。 */
    @Test
    public void insertInsideSpringTransaction() {
        TransactionTemplate tx = new TransactionTemplate(txManager);
        ItUser fourth = new ItUser("Dave", 30);
        tx.execute(status -> service.insert(fourth));
        Assert.assertEquals("有事务：自增 id 应回填", Long.valueOf(1L), fourth.getId());
    }

    /** 存在 Spring 事务：异常回滚后数据不应落库。 */
    @Test
    public void transactionRollbackDoesNotPersist() {
        int beforeRollback = service.count();
        TransactionTemplate tx = new TransactionTemplate(txManager);
        try {
            tx.execute(status -> {
                service.insert(new ItUser("Rollback", 40));
                throw new IllegalStateException("rollback for test");
            });
            Assert.fail("应抛出 IllegalStateException 以触发回滚");
        } catch (IllegalStateException expected) {
            // 预期异常
        }
        Assert.assertEquals("有事务：回滚后数据不应落库", beforeRollback, service.count());
    }

    /** 事务结束后连接未泄漏：仍能继续插入。 */
    @Test
    public void connectionUsableAfterTransaction() {
        TransactionTemplate tx = new TransactionTemplate(txManager);
        tx.execute(status -> service.insert(new ItUser("Eve", 50)));

        ItUser afterTx = new ItUser("Frank", 60);
        Assert.assertEquals("事务之后应能继续插入", 1, service.insert(afterTx));
        Assert.assertNotNull("事务之后自增 id 应正常回填", afterTx.getId());
    }
}
